### ISSUE TITLE
X509_Certificate shouldn't check private key in a 2 level PKI.

### ISSUE THREAD

**Issue by luclis** [ansible-collections/community.crypto#376] opened 2022-01-11 10:42 UTC
##### SUMMARY
I want to run an 2 two level PKI. In my logic, the root one should have only is key and the certificates he publish (typically himself and the delegated). The delegated should have only is key, the root certificate and the certificates he publish (the clients). 
When I first run the playbook, everythings is fine, the delegated ca is well created and fonctionnal. But if I try to re-run it (let's say for renew the certificates when they're expired), the module look up for the delegated private key file and goes in error. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.crypto.x509_certificate

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.1]
  config file = /home/user-ansible/PADAWAN/ansible.cfg
  configured module search path = ['/home/user-ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user-ansible/ansible/lib/python3.8/site-packages/ansible
  ansible collection location = /home/user-ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user-ansible/ansible/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection        Version
----------------- -------
community.crypto  2.1.0  
community.general 4.3.0  
```

##### CONFIGURATION
  
```paste below
DEFAULT_HOST_LIST(/home/user-ansible/example/ansible.cfg) = ['/home/user-ansible/example/inventaire.yml']
HOST_KEY_CHECKING(/home/user-ansible/example/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/user-ansible/example/ansible.cfg) = False
TAGS_SKIP(/home/user-ansible/example/ansible.cfg) = ['no-internet', 'init_plateform']

```

##### OS / ENVIRONMENT

Ubuntu LTS on node side and Debian 11 on server side.

##### STEPS TO REPRODUCE

* Create 2 vm : the node who'll keep the root ca and the certif who'll keep the delegated ca.
* Install ansible and everything needed by `community.crypto` 
* Set the first level of the PKI.
* Run [this task.](https://gist.github.com/luclis/fca0664a0aaa83ddfd71d60da4e87866)
* Run it twice.
##### EXPECTED RESULTS

The second run should bypass the step as the certificate is created and well formating according to what he should know.

##### ACTUAL RESULTS

```paste below
TASK [ansible-role-certifs : Sign certificate.] ***********************************************************************************************************************************************************
task path: /home/user-ansible/example/roles/ansible-role-certifs/tasks/authority.yml:102
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: user-ansible
<localhost> EXEC /bin/sh -c 'echo ~user-ansible && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/user-ansible/.ansible/tmp `"&& mkdir "` echo /home/user-ansible/.ansible/tmp/ansible-tmp-1641895591.6986313-76610-75008454743692 `" && echo ansible-tmp-1641895591.6986313-76610-75008454743692="` echo /home/user-ansible/.ansible/tmp/ansible-tmp-1641895591.6986313-76610-75008454743692 `" ) && sleep 0'
Using module file /home/user-ansible/.ansible/collections/ansible_collections/community/crypto/plugins/modules/x509_certificate.py
<localhost> PUT /home/user-ansible/.ansible/tmp/ansible-local-75448jojil4bh/tmplf0vfhb5 TO /home/user-ansible/.ansible/tmp/ansible-tmp-1641895591.6986313-76610-75008454743692/AnsiballZ_x509_certificate.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/user-ansible/.ansible/tmp/ansible-tmp-1641895591.6986313-76610-75008454743692/ /home/user-ansible/.ansible/tmp/ansible-tmp-1641895591.6986313-76610-75008454743692/AnsiballZ_x509_certificate.py && sleep 0'
<localhost> EXEC /bin/sh -c 'sudo -H -S -n  -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-hpbfpzfhojkvqajozybcyaqecwtsyory ; /home/user-ansible/ansible/bin/python /home/user-ansible/.ansible/tmp/ansible-tmp-1641895591.6986313-76610-75008454743692/AnsiballZ_x509_certificate.py'"'"' && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/user-ansible/.ansible/tmp/ansible-tmp-1641895591.6986313-76610-75008454743692/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_community.crypto.x509_certificate_payload_i_p9q15x/ansible_community.crypto.x509_certificate_payload.zip/ansible_collections/community/crypto/plugins/modules/x509_certificate.py", line 404, in main
  File "/tmp/ansible_community.crypto.x509_certificate_payload_i_p9q15x/ansible_community.crypto.x509_certificate_payload.zip/ansible_collections/community/crypto/plugins/modules/x509_certificate.py", line 326, in generate
  File "/tmp/ansible_community.crypto.x509_certificate_payload_i_p9q15x/ansible_community.crypto.x509_certificate_payload.zip/ansible_collections/community/crypto/plugins/module_utils/crypto/module_backends/certificate_ownca.py", line 173, in needs_regeneration
    if super(OwnCACertificateBackendCryptography, self).needs_regeneration(not_before=self.notBefore, not_after=self.notAfter):
  File "/tmp/ansible_community.crypto.x509_certificate_payload_i_p9q15x/ansible_community.crypto.x509_certificate_payload.zip/ansible_collections/community/crypto/plugins/module_utils/crypto/module_backends/certificate.py", line 238, in needs_regeneration
    self._ensure_private_key_loaded()
  File "/tmp/ansible_community.crypto.x509_certificate_payload_i_p9q15x/ansible_community.crypto.x509_certificate_payload.zip/ansible_collections/community/crypto/plugins/module_utils/crypto/module_backends/certificate.py", line 130, in _ensure_private_key_loaded
    self.privatekey = load_privatekey(
  File "/tmp/ansible_community.crypto.x509_certificate_payload_i_p9q15x/ansible_community.crypto.x509_certificate_payload.zip/ansible_collections/community/crypto/plugins/module_utils/crypto/support.py", line 135, in load_privatekey
    raise OpenSSLObjectError(exc)
fatal: [certif.example.com -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "acme_accountkey_path": null,
            "acme_chain": false,
            "acme_challenge_path": null,
            "acme_directory": "https://acme-v02.api.letsencrypt.org/directory",
            "attributes": null,
            "backup": false,
            "csr_content": "-----BEGIN CERTIFICATE REQUEST-----\CSR-CONTENT\n-----END CERTIFICATE REQUEST-----\n",
            "csr_path": null,
            "entrust_api_client_cert_key_path": null,
            "entrust_api_client_cert_path": null,
            "entrust_api_key": null,
            "entrust_api_specification_path": "https://cloud.entrust.net/EntrustCloud/documentation/cms-api-2.1.0.yaml",
            "entrust_api_user": null,
            "entrust_cert_type": "STANDARD_SSL",
            "entrust_not_after": "+365d",
            "entrust_requester_email": null,
            "entrust_requester_name": null,
            "entrust_requester_phone": null,
            "force": false,
            "group": "root",
            "ignore_timestamps": true,
            "mode": 384,
            "ownca_content": null,
            "ownca_create_authority_key_identifier": true,
            "ownca_create_subject_key_identifier": "create_if_not_provided",
            "ownca_digest": "sha512",
            "ownca_not_after": "+1825d",
            "ownca_not_before": "+0s",
            "ownca_path": "/srv/PKI/padawan.local/root_ca/public/ACR_PADAWAN.LOCAL.pem",
            "ownca_privatekey_content": null,
            "ownca_privatekey_passphrase": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "ownca_privatekey_path": "/path/of/the/private/key/existing/only/on/the/node/server/name.key",
            "ownca_version": 3,
            "owner": "root",
            "path": "/path/of/the/public/key/existing/on/both/servers/name.key",",
            "privatekey_content": null,
            "privatekey_passphrase": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "privatekey_path":  "/path/of/the/private/key/existing/only/on/the/certif/server/name.key",
            "provider": "ownca",
            "return_content": true,
            "select_crypto_backend": "auto",
            "selevel": null,
            "selfsigned_create_subject_key_identifier": "create_if_not_provided",
            "selfsigned_digest": "sha512",
            "selfsigned_not_after": "+1825d",
            "selfsigned_not_before": "+0s",
            "selfsigned_version": 3,
            "serole": null,
            "setype": null,
            "seuser": null,
            "state": "present",
            "unsafe_writes": false
        }
    },
    "msg": "[Errno 2] No file or folder: '/path/of/the/private/key/existing/only/on/the/certif/server/name.key'"
}
```

In my opinion, this module shouldn't rise an error or at least, we should say it to do not check the private key.

**Comment by felixfontein** [comment] 2022-01-11 12:55
The tasks you linked to (https://gist.github.com/luclis/fca0664a0aaa83ddfd71d60da4e87866) should not produce such an error when run twice. So apparently you are doing something that's not shown here? Why is the private key file for the certificate no longer present on the second run? (Also the `openssl_privatekey` task should simply create a new one if it has been deleted before, so this really cannot happen with the tasks you have linked to.)

**Comment by felixfontein** [comment] 2022-01-11 12:58
(Also, why do you pass `privatekey_path` to `x509_certificate` when `provider=ownca` in the first place? It is not needed. If the private key is passed, it tries to validate whether the certificate is actually signed by the private key, so if you specify `privatekey_path`, the path must point to an existing file.)

**Comment by luclis** [comment] 2022-01-11 15:35
Hi @felixfontein and thanks your for your answer. 
My whole playbook is a bit more complexe : with the same file `authority.yaml`, i'm generating first the Root Ca then the Delegated one. So I need tho have `privatekey_path` for selfsigning the first root ca. 

As I said before, the certificate is no longer present because it's not on the same VM. 

It's still work in progress but if you want to see the whole playbook, it's [here](https://github.com/luclis/ansible-role-certifs)

**Comment by felixfontein** [comment] 2022-01-12 07:35
If the private key never existed on this VM, why did the task pass on this VM before?

**Comment by luclis** [comment] 2022-01-12 08:59
I don't exactly know but i suppose the first time, `x509_certificate` take the csr passed as variable and sign it without any more check. The second time, i think `x509_certificate` see an already existing certificate and try to check if the certificate match to the private key. What he can't do because he doesn't have it. 

I can workaround with an `ignore_errors: yes` (doesn't try) but I think I'll not be able to regenerate them when they'll expire.

**Comment by felixfontein** [comment] 2022-02-12 11:26
I don't think this is anything we want to change on the module's side. You need to write your role/playbook so that you only pass parameters that make sense, for example by first checking whether the file exists. I'm closing this issue, in particular because this is not a bug, but intended behavior.

**Closed by felixfontein** 2022-02-12 11:26 UTC
Labels: question
